server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security/
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update